#!/usr/bin/env python3
"""
worldgen.py — Fabula Ultima session zero. Walks the world / group / character creation
procedure from data/worldgen.json, writes campaign/world.json, and regenerates
bridge/setting-canon.md (the live committed world). FU has no default setting.

  worldgen.py steps                 # print the ordered creation prompts + choices
  worldgen.py run [--demo]          # scaffold campaign/world.json + regenerate canon
                                    #   --demo fills example content for a dry run
  worldgen.py canon                 # regenerate bridge/setting-canon.md from world.json

No randomness of consequence here; any suggestion rolls would route through engine.py.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fudata as F

CANON = os.path.join(F.ROOT, "bridge", "setting-canon.md")

DEMO = {
    "shape": "A ring of floating continents around a dead sun, linked by skyferries.",
    "map": "Four skylands: verdant Aurelia, storm-wracked Kesh, the ashen Cinderreach, and the imperial hub of Valmont.",
    "magic_and_technology": "High magic, low technology — soulcraft and airships, no firearms in common use.",
    "kingdoms_and_nations": "The Valmont Ascendancy (expansionist), the Free Cantons of Aurelia, the Kesh stormclans.",
    "historical_events": "The Sundering that shattered the old world; the Skyferry Accords; the last Emperor's disappearance.",
    "enigmas_and_mysteries": "What put out the sun? Where did the last Emperor go? What sleeps beneath the Cinderreach?",
    "threats": "The Ascendancy's war fleet; a cult worshipping the dead sun; a returning archdemon of ash.",
}


def _steps(phase):
    return F.load("worldgen").get(phase, {}).get("steps", [])


def cmd_steps(_a):
    wg = F.load("worldgen")
    for phase in ("world_creation", "group_creation", "character_creation"):
        print(f"\n=== {phase.replace('_', ' ').title()} ===")
        meta = wg.get(phase, {})
        for extra in ("starting_zenit", "starting_classes"):
            if extra in meta:
                print(f"  ({extra}: {meta[extra]})")
        for i, s in enumerate(_steps(phase), 1):
            print(f"  {i}. [{s['key']}] {s.get('prompt', s.get('text', ''))}")
            for c in s.get("choices", []) or []:
                print(f"        - {c}")
    return 0


def cmd_run(a):
    world = {"world": {}, "group": {}, "characters": []}
    for s in _steps("world_creation"):
        k = s["key"]
        world["world"][k] = DEMO.get(k, "") if a.demo else ""
    for s in _steps("group_creation"):
        world["group"][s["key"]] = ("A band of skyfarers bound by a shared debt to Valmont."
                                    if a.demo else "")
    world["_prompts"] = {s["key"]: s.get("prompt", "") for s in _steps("world_creation")}
    # genre defaults (magic/tech level, featured classes) + set the campaign genre
    gk = a.genre or "core"
    world["genre"] = gk
    g = next((x for x in F.load("genre")["genres"] if x["key"] == gk), None)
    if g:
        world["featured_classes"] = g.get("featured_classes", [])
        if not world["world"].get("magic_and_technology"):
            world["world"]["magic_and_technology"] = (
                f"magic: {g['magic_level']}, technology: {g['tech_level']}  ({g['name']})")
        import state as S
        st = S.load_state(); st["genre"] = gk; st["chaos"] = g["chaos"]["start"]
        S.save_state(st)
    F.write_state("world.json", world)
    render_canon(world)
    print(f"🌍 wrote {os.path.join(F.CAMPAIGN, 'world.json')} and regenerated {CANON}")
    if not a.demo:
        print("   fill in campaign/world.json (or edit the canon), then `worldgen.py canon`.")
    return 0


def cmd_canon(_a):
    world = F.read_state("world.json", None)
    if not world:
        sys.exit("no campaign/world.json — run `worldgen.py run` first.")
    render_canon(world)
    print(f"↻ regenerated {CANON}")
    return 0


def render_canon(world):
    w = world.get("world", {})
    prompts = world.get("_prompts", {})
    lines = [
        "<!-- GENERATED by scripts/worldgen.py from campaign/world.json — do not hand-edit. -->",
        "# Setting Canon — Fabula Ultima",
        "",
        "The world created at session zero. This is the live ground truth and overrides recollection.",
        "",
    ]
    if world.get("genre"):
        lines.append(f"**Genre:** {world['genre']}"
                     + (f"  ·  featured classes: {', '.join(world.get('featured_classes', []))}"
                        if world.get("featured_classes") else ""))
        lines.append("")
    labels = {
        "shape": "Shape of the World", "map": "The Map",
        "magic_and_technology": "Magic & Technology",
        "kingdoms_and_nations": "Kingdoms & Nations",
        "historical_events": "Historical Events",
        "enigmas_and_mysteries": "Enigmas & Mysteries", "threats": "Threats",
    }
    for k in ["shape", "map", "magic_and_technology", "kingdoms_and_nations",
              "historical_events", "enigmas_and_mysteries", "threats"]:
        if k not in w:
            continue
        lines.append(f"## {labels.get(k, k)}")
        val = w.get(k, "").strip()
        lines.append(val if val else f"_TODO: {prompts.get(k, k)}_")
        lines.append("")
    grp = world.get("group", {})
    if grp:
        lines.append("## The Group")
        for gk, gv in grp.items():
            lines.append(f"- **{gk}**: {gv or '_TODO_'}")
        lines.append("")
    cast = world.get("characters", [])
    if cast:
        lines.append("## Starting Cast")
        for c in cast:
            lines.append(f"- {c.get('name','?')} — {c.get('identity','')}")
        lines.append("")
    os.makedirs(os.path.dirname(CANON), exist_ok=True)
    with open(CANON, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")


def main(argv):
    p = argparse.ArgumentParser(prog="worldgen.py")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("steps").set_defaults(fn=cmd_steps)
    r = sub.add_parser("run"); r.add_argument("--demo", action="store_true")
    r.add_argument("--genre", choices=["core", "high", "natural", "techno"]); r.set_defaults(fn=cmd_run)
    sub.add_parser("canon").set_defaults(fn=cmd_canon)
    a = p.parse_args(argv)
    return a.fn(a)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
